name: Core
version: '1.0'
main: org.core.Main.Core
api-version: '1.21.8'
commands:
  core:
    description: "core"
    usage: "/core"
  coreclear:
    description: "coreclear"
    usage: "/coreclear"
  corecheck:
    description: "coreclear"
    usage: "/coreclear"
  corelevelreset:
    description: "corelevelreset"
    usage: "/corelevelreset"
  corelevelset:
    description: "corelevelset"
    usage: "/corelevelset"
  coredbpaste:
    description: "coredbpaste"
    usage: "/coredbpaste"
  coredbupdate:
    description: "coredbupdate"
    usage: "/coredbupdate"
  gc:
    description: "gc"
    usage: "/gc"
