name: Core
version: '1.0'
main: org.core.Core
api-version: '1.21.6'
commands:
  core:
    description: "core"
    usage: "/core"
  coreclear:
    description: "coreclear"
    usage: "/coreclear"
  corecheck:
    description: "coreclear"
    usage: "/coreclear"
  corelevelreset:
    description: "corelevelreset"
    usage: "/coreLevelReset"
  corelevelset:
    description: "corelevelset"
    usage: "/corelevelset"

  gc:
    description: "gc"
    usage: "/gc"
